sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  cloudinary:
    cloud-name: djr2j9kpg
    api-key: 842828246414883
    api-secret: 7AKgj0bCLh0tcwaqsqe0i048YEQ

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx9fb77ea242016de6
    secret: d04bf1099f342d2005d0145547896aad
    mchid: 1558950191
    mchSerialNo: 商户API证书序列号
    privateKeyFilePath: D:/cert/apiclient_key.pem
    apiV3Key: apiV3密钥
    weChatPayCertFilePath: D:/cert/wechatpayCert.pem
    notifyUrl: https://ca7261b.r21.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://ca7261b.r21.cpolar.top/notify/refundSuccess